// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQplRszraAm4wvwo_y0CnqVjNoI7274xk',
    appId: '1:101680904447:web:cc3abb4d645a87dc5f74ca',
    messagingSenderId: '101680904447',
    projectId: 'reddit-68a81',
    authDomain: 'reddit-68a81.firebaseapp.com',
    storageBucket: 'reddit-68a81.appspot.com',
    measurementId: 'G-NFZYX82WZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKvXRNhngrVxtPErFBH-RiVZMlxlOOg7g',
    appId: '1:101680904447:android:cc2d647c8d2f8c2a5f74ca',
    messagingSenderId: '101680904447',
    projectId: 'reddit-68a81',
    storageBucket: 'reddit-68a81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_XWGfSe8RMMjaa5rNArhngCEH2tfEGmI',
    appId: '1:101680904447:ios:4095b8e0af40818b5f74ca',
    messagingSenderId: '101680904447',
    projectId: 'reddit-68a81',
    storageBucket: 'reddit-68a81.appspot.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_XWGfSe8RMMjaa5rNArhngCEH2tfEGmI',
    appId: '1:101680904447:ios:4095b8e0af40818b5f74ca',
    messagingSenderId: '101680904447',
    projectId: 'reddit-68a81',
    storageBucket: 'reddit-68a81.appspot.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQplRszraAm4wvwo_y0CnqVjNoI7274xk',
    appId: '1:101680904447:web:28850020f18c14655f74ca',
    messagingSenderId: '101680904447',
    projectId: 'reddit-68a81',
    authDomain: 'reddit-68a81.firebaseapp.com',
    storageBucket: 'reddit-68a81.appspot.com',
    measurementId: 'G-TVR9YMMKYS',
  );
}
